### PR TITLE
Fix safari stuff and replace some tweets | Fix #343

### LINKED ISSUE #343: Improve landing page display in Safari
- The twitter widget looks broken
- Some diagonals needs more love

### PR DESCRIPTION
**Pull request by LukyVj**

### CODE REVIEW

**Comment by LukyVj** [comment]
cc @rayrutjes

File: docs/src/js/app.js [hunk 1]
```diff
@@ -1,4 +1,11 @@
 
+
+ window.onload = function(){
+  if ( navigator.userAgent.indexOf('Safari') != -1 ) {
+    document.body.classList.add('safari')
```
Comment (rayrutjes) [inline docs/src/js/app.js]: Thanks @Haroenv for jumping in, @LukyVj could you take a look?

**Comment by LukyVj** [comment]
Sure, ill do it tomorow
